[package]
name = "utils_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "utils_rs"
crate-type = ["cdylib"]

[dependencies]
bio = "1.4.0"
indexmap = "2.0.2"
itertools = "0.11.0"
pyo3 = "0.19.0"
