## PARAMETERS FOR PLOTTING VCF

# General options
devpars = {width = 1000, height = 1000, res = 200}
passed = true

# Plots
[[instance]]
formula = 'DEPTHs{0} ~ CHROM'
title = 'Depth distribution on each Mitogenome'
ggs = 'theme_dark(); ylab("Read-depth")'
figtype = 'violin'

[[instance]]
formula = 'COUNT(1, group=VARTYPE) ~ CHROM'
title = 'Types of variants on Mitogenome'
ggs = 'theme_light(); ylab("Count")'
figtype = 'bar'

[[instance]]
formula = 'AAF ~ CHROM'
title = 'Allele frequency on each Mitogenome'
ggs = 'theme_light()'
figtype = 'density'

[[instance]]
formula = 'AAF ~ 1'
title = 'Overall allele frequency distribution' 
ggs = 'theme_light()'
figtype = 'histogram'

[[instance]]
formula = 'COUNT(1, VARTYPE[snp]) ~ SUBST[A>T,A>G,A>C,T>A,T>G,T>C,G>A,G>T,G>C,C>A,C>T,C>G]'
title = 'Number of substitutions of SNPs'
ggs = 'theme_light(); ylab("Count")'
figtype = 'col'

[[instance]]
formula = 'COUNT(1) ~ CHROM'
title = 'Number of Variants at each Mitogenome'
ggs = 'theme_light(); ylab("Count")'
figtype = 'col'

[[instance]]
formula = 'COUNT(1) ~ TITV'
title = 'Number of TiTv at Mitogenome'
ggs = 'theme_light(); ylab("Count")'
figtype = 'bar'

[[instance]]
formula = 'DEPTHs ~ 1'
title = 'Number of positions per depth'
ggs = 'stat_bin(bins=5);theme_light(); ylab("# Positions");xlab("Read-depth")'
figtype = 'histogram'